//! Shared serde data structures for the decrypted vault model.
//!
//! This module defines the **plaintext, in-memory shape** of a Keyhaven vault:
//! the entries, their flexible fields, user-defined custom services, and the
//! user's settings. None of these types ever touch disk in the clear — the
//! whole [`VaultModel`] is JSON-serialized, compressed, and then encrypted
//! (XChaCha20-Poly1305 under the VEK) by the vault format layer (task 3.3).
//!
//! ## Serde conventions
//!
//! - [`ServiceRef`] and [`IconRef`] are **tagged unions** keyed by `kind`
//!   (`#[serde(tag = "kind", rename_all = "lowercase")]`), matching the design's
//!   `{ "kind": "catalog", "id": "..." }` / `{ "kind": "builtin", "ref": "..." }`
//!   wire shapes.
//! - [`FieldType`] serializes as `snake_case` so `TotpSecret`/`RecoveryCode`
//!   become `totp_secret`/`recovery_code` (Req 5.4, 7.6).
//! - The Rust keyword `type` cannot be a field name, so [`Field::field_type`] is
//!   renamed to `type` on the wire (`#[serde(rename = "type")]`).
//!
//! ## (De)serialization + compression (Req 5.4, 7.6, 12.5)
//!
//! [`serialize_vault`] performs JSON serialization followed by DEFLATE
//! compression, and [`deserialize_vault`] reverses it. Together they guarantee
//! **round-trip fidelity** (Property 1): for any valid model `m`,
//! `deserialize_vault(serialize_vault(m)) == m`. Compression keeps the encrypted
//! payload small without affecting fidelity.

// Some constructors/fields are consumed by later tasks (repository, commands)
// and are not yet referenced from the binary while the core is built bottom-up.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};

use flate2::read::ZlibDecoder;
use flate2::write::ZlibEncoder;
use flate2::Compression;
use std::io::{Read, Write};

/// The schema version embedded in every serialized vault model.
///
/// This is distinct from the binary file-format version in the vault header: it
/// versions the *decrypted payload* shape so future migrations can detect and
/// upgrade older models after decryption.
pub const SCHEMA_VERSION: u32 = 1;

/// The complete decrypted vault, as held in memory while unlocked and as
/// serialized into the encrypted payload.
///
/// Settings are stored **inside** the encrypted model (Req 4.x / 12.5) so they
/// are protected at rest alongside the entries rather than living in a separate
/// plaintext file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VaultModel {
    /// Payload schema version; see [`SCHEMA_VERSION`].
    pub schema_version: u32,
    /// All stored entries (credentials/records).
    #[serde(default)]
    pub entries: Vec<Entry>,
    /// User-defined services not present in the bundled catalog (Req 6.x).
    #[serde(default)]
    pub custom_services: Vec<CustomService>,
    /// User settings, persisted encrypted within the vault.
    #[serde(default)]
    pub settings: Settings,
}

impl VaultModel {
    /// Create an empty vault model at the current [`SCHEMA_VERSION`] with
    /// default settings — the starting point for a freshly created vault.
    pub fn new() -> Self {
        VaultModel {
            schema_version: SCHEMA_VERSION,
            entries: Vec::new(),
            custom_services: Vec::new(),
            settings: Settings::default(),
        }
    }
}

impl Default for VaultModel {
    fn default() -> Self {
        VaultModel::new()
    }
}

/// A single stored record (e.g. a login for one service).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Entry {
    /// Stable unique identifier (UUID v4 string). Generated by the repository
    /// layer (task 6.1); this module only stores it.
    pub id: String,
    /// Which service this entry is for — a catalog reference or a custom one.
    pub service_ref: ServiceRef,
    /// Optional user-supplied label distinguishing entries for the same service
    /// (e.g. "Personal Facebook").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The entry's flexible fields (Req 7.x).
    #[serde(default)]
    pub fields: Vec<Field>,
    /// Creation timestamp (ISO-8601 string).
    pub created_at: String,
    /// Last-update timestamp (ISO-8601 string).
    pub updated_at: String,
}

/// Reference to the service an [`Entry`] belongs to.
///
/// A tagged union on `kind`: either a bundled catalog service (`catalog`) or a
/// user-defined custom service (`custom`), each identified by its `id`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum ServiceRef {
    /// A service from the bundled catalog; `id` is the catalog service id (e.g. `"facebook"`).
    Catalog {
        /// Catalog service identifier.
        id: String,
    },
    /// A user-defined custom service; `id` references a [`CustomService::id`].
    Custom {
        /// Custom service identifier (UUID string).
        id: String,
    },
}

/// One field within an [`Entry`].
///
/// Fields are fully flexible: any number, with custom labels, and an arbitrary
/// [`FieldType`]. The [`secret`](Field::secret) flag drives masking, clipboard
/// auto-clear, and — importantly — exclusion from the search index (Req 9.x).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Field {
    /// Stable field identifier (unique within the entry).
    pub id: String,
    /// Human-readable label (e.g. "Email", "Recovery code").
    pub label: String,
    /// Semantic type of the field. Serialized as `type` on the wire.
    #[serde(rename = "type")]
    pub field_type: FieldType,
    /// The field's value (plaintext within the decrypted model).
    pub value: String,
    /// Whether this value is sensitive: masked in the UI, auto-cleared from the
    /// clipboard, and never placed in the search index.
    pub secret: bool,
}

/// Semantic type of an entry [`Field`].
///
/// Serializes in `snake_case` to match the design wire values
/// (`email | username | password | phone | url | text | note | totp_secret |
/// recovery_code`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FieldType {
    /// An email address.
    Email,
    /// A username / login handle.
    Username,
    /// A password (typically secret).
    Password,
    /// A phone number.
    Phone,
    /// A URL.
    Url,
    /// Free-form short text.
    Text,
    /// A longer free-form note.
    Note,
    /// A TOTP shared secret (typically secret).
    TotpSecret,
    /// A backup/recovery code (typically secret).
    RecoveryCode,
}

/// A user-defined service not present in the bundled catalog (Req 6.x).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CustomService {
    /// Stable unique identifier (UUID string) referenced by
    /// [`ServiceRef::Custom`].
    pub id: String,
    /// Display name of the service (e.g. "My Home Server").
    pub name: String,
    /// Icon for the service.
    pub icon: IconRef,
}

/// Reference to an icon used by a service.
///
/// A tagged union on `kind`: a bundled/built-in icon (`builtin`, where `ref` is
/// an icon name/path) or an inline data icon (`data`, where `ref` is a data
/// URI or base64 blob).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum IconRef {
    /// A built-in/bundled icon; `ref` identifies it (e.g. `"facebook.svg"`).
    Builtin {
        /// Icon reference (name or path).
        #[serde(rename = "ref")]
        reference: String,
    },
    /// An inline data icon; `ref` carries the data (e.g. a data URI).
    Data {
        /// Inline icon data.
        #[serde(rename = "ref")]
        reference: String,
    },
}

/// User settings, stored encrypted within the vault model.
///
/// Defaults follow the design: 5-minute auto-lock, lock-on-blur off, 20-second
/// clipboard clear, and 20-character generated passwords across all character
/// classes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Settings {
    /// Inactivity timeout before auto-lock, in seconds. `0` disables auto-lock.
    pub auto_lock_seconds: u32,
    /// Whether the vault locks when the window loses focus/minimizes.
    pub lock_on_blur: bool,
    /// Delay before a copied secret is cleared from the clipboard, in seconds.
    pub clipboard_clear_seconds: u32,
    /// Default options for the password generator.
    pub password_gen_defaults: PasswordGenDefaults,
}

impl Default for Settings {
    fn default() -> Self {
        Settings {
            auto_lock_seconds: 300,
            lock_on_blur: false,
            clipboard_clear_seconds: 20,
            password_gen_defaults: PasswordGenDefaults::default(),
        }
    }
}

/// Default character-class and length options for the password generator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct PasswordGenDefaults {
    /// Generated password length.
    pub length: u32,
    /// Include uppercase letters.
    pub upper: bool,
    /// Include lowercase letters.
    pub lower: bool,
    /// Include digits.
    pub digits: bool,
    /// Include symbols.
    pub symbols: bool,
}

impl Default for PasswordGenDefaults {
    fn default() -> Self {
        PasswordGenDefaults {
            length: 20,
            upper: true,
            lower: true,
            digits: true,
            symbols: true,
        }
    }
}

/// Errors from serializing/deserializing the decrypted vault model.
#[derive(Debug)]
pub enum ModelError {
    /// JSON (de)serialization failed.
    Json(serde_json::Error),
    /// Compression or decompression failed (e.g. corrupt/truncated payload).
    Compression(std::io::Error),
}

impl std::fmt::Display for ModelError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ModelError::Json(e) => write!(f, "vault model JSON error: {e}"),
            ModelError::Compression(e) => write!(f, "vault model compression error: {e}"),
        }
    }
}

impl std::error::Error for ModelError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ModelError::Json(e) => Some(e),
            ModelError::Compression(e) => Some(e),
        }
    }
}

impl From<serde_json::Error> for ModelError {
    fn from(e: serde_json::Error) -> Self {
        ModelError::Json(e)
    }
}

/// Serialize a [`VaultModel`] to compressed bytes: JSON-encode, then DEFLATE
/// (zlib) compress.
///
/// The output is the plaintext payload that the vault format layer encrypts
/// under the VEK. Paired with [`deserialize_vault`] this guarantees round-trip
/// fidelity (Property 1).
pub fn serialize_vault(model: &VaultModel) -> Result<Vec<u8>, ModelError> {
    let json = serde_json::to_vec(model)?;

    let mut encoder = ZlibEncoder::new(Vec::new(), Compression::default());
    encoder
        .write_all(&json)
        .map_err(ModelError::Compression)?;
    encoder.finish().map_err(ModelError::Compression)
}

/// Deserialize a [`VaultModel`] from compressed bytes produced by
/// [`serialize_vault`]: DEFLATE-decompress, then JSON-decode.
///
/// Returns [`ModelError::Compression`] for corrupt/truncated compressed input
/// and [`ModelError::Json`] for structurally invalid JSON.
pub fn deserialize_vault(bytes: &[u8]) -> Result<VaultModel, ModelError> {
    let mut decoder = ZlibDecoder::new(bytes);
    let mut json = Vec::new();
    decoder
        .read_to_end(&mut json)
        .map_err(ModelError::Compression)?;

    let model = serde_json::from_slice(&json)?;
    Ok(model)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a representative, fully-populated model exercising every variant.
    fn sample_model() -> VaultModel {
        VaultModel {
            schema_version: SCHEMA_VERSION,
            entries: vec![
                Entry {
                    id: "11111111-1111-4111-8111-111111111111".to_string(),
                    service_ref: ServiceRef::Catalog {
                        id: "facebook".to_string(),
                    },
                    title: Some("Personal Facebook".to_string()),
                    fields: vec![
                        Field {
                            id: "f1".to_string(),
                            label: "Email".to_string(),
                            field_type: FieldType::Email,
                            value: "me@example.com".to_string(),
                            secret: false,
                        },
                        Field {
                            id: "f2".to_string(),
                            label: "Password".to_string(),
                            field_type: FieldType::Password,
                            value: "hunter2".to_string(),
                            secret: true,
                        },
                    ],
                    created_at: "2024-01-01T00:00:00Z".to_string(),
                    updated_at: "2024-01-02T00:00:00Z".to_string(),
                },
                Entry {
                    id: "22222222-2222-4222-8222-222222222222".to_string(),
                    service_ref: ServiceRef::Custom {
                        id: "custom-uuid".to_string(),
                    },
                    title: None,
                    fields: vec![Field {
                        id: "f3".to_string(),
                        label: "Recovery code".to_string(),
                        field_type: FieldType::RecoveryCode,
                        value: "ABCD-EFGH".to_string(),
                        secret: true,
                    }],
                    created_at: "2024-02-01T00:00:00Z".to_string(),
                    updated_at: "2024-02-01T00:00:00Z".to_string(),
                },
            ],
            custom_services: vec![CustomService {
                id: "custom-uuid".to_string(),
                name: "My Home Server".to_string(),
                icon: IconRef::Data {
                    reference: "data:image/png;base64,AAAA".to_string(),
                },
            }],
            settings: Settings::default(),
        }
    }

    #[test]
    fn settings_defaults_match_design() {
        let s = Settings::default();
        assert_eq!(s.auto_lock_seconds, 300);
        assert!(!s.lock_on_blur);
        assert_eq!(s.clipboard_clear_seconds, 20);
        assert_eq!(
            s.password_gen_defaults,
            PasswordGenDefaults {
                length: 20,
                upper: true,
                lower: true,
                digits: true,
                symbols: true,
            }
        );
    }

    #[test]
    fn empty_model_uses_current_schema_and_default_settings() {
        let m = VaultModel::new();
        assert_eq!(m.schema_version, SCHEMA_VERSION);
        assert!(m.entries.is_empty());
        assert!(m.custom_services.is_empty());
        assert_eq!(m.settings, Settings::default());
    }

    #[test]
    fn field_type_serializes_as_snake_case() {
        assert_eq!(
            serde_json::to_string(&FieldType::TotpSecret).unwrap(),
            "\"totp_secret\""
        );
        assert_eq!(
            serde_json::to_string(&FieldType::RecoveryCode).unwrap(),
            "\"recovery_code\""
        );
        assert_eq!(
            serde_json::to_string(&FieldType::Email).unwrap(),
            "\"email\""
        );
        // And it round-trips back.
        let parsed: FieldType = serde_json::from_str("\"totp_secret\"").unwrap();
        assert_eq!(parsed, FieldType::TotpSecret);
    }

    #[test]
    fn service_ref_uses_kind_tag() {
        let catalog = ServiceRef::Catalog {
            id: "facebook".to_string(),
        };
        let json: serde_json::Value =
            serde_json::from_str(&serde_json::to_string(&catalog).unwrap()).unwrap();
        assert_eq!(json["kind"], "catalog");
        assert_eq!(json["id"], "facebook");

        let custom = ServiceRef::Custom {
            id: "custom-uuid".to_string(),
        };
        let json: serde_json::Value =
            serde_json::from_str(&serde_json::to_string(&custom).unwrap()).unwrap();
        assert_eq!(json["kind"], "custom");
        assert_eq!(json["id"], "custom-uuid");
    }

    #[test]
    fn icon_ref_uses_kind_tag_and_ref_field() {
        let builtin = IconRef::Builtin {
            reference: "facebook.svg".to_string(),
        };
        let json: serde_json::Value =
            serde_json::from_str(&serde_json::to_string(&builtin).unwrap()).unwrap();
        assert_eq!(json["kind"], "builtin");
        // The Rust field `reference` must serialize as `ref` on the wire.
        assert_eq!(json["ref"], "facebook.svg");

        let data = IconRef::Data {
            reference: "data:...".to_string(),
        };
        let json: serde_json::Value =
            serde_json::from_str(&serde_json::to_string(&data).unwrap()).unwrap();
        assert_eq!(json["kind"], "data");
        assert_eq!(json["ref"], "data:...");
    }

    #[test]
    fn field_serializes_type_key() {
        let field = Field {
            id: "f1".to_string(),
            label: "Email".to_string(),
            field_type: FieldType::Email,
            value: "me@example.com".to_string(),
            secret: false,
        };
        let json: serde_json::Value =
            serde_json::from_str(&serde_json::to_string(&field).unwrap()).unwrap();
        // `field_type` must appear as `type` on the wire (Rust keyword workaround).
        assert_eq!(json["type"], "email");
        assert_eq!(json["label"], "Email");
        assert_eq!(json["secret"], false);
    }

    #[test]
    fn optional_title_is_omitted_when_none() {
        let entry = Entry {
            id: "id".to_string(),
            service_ref: ServiceRef::Catalog {
                id: "x".to_string(),
            },
            title: None,
            fields: vec![],
            created_at: "t".to_string(),
            updated_at: "t".to_string(),
        };
        let json: serde_json::Value =
            serde_json::from_str(&serde_json::to_string(&entry).unwrap()).unwrap();
        assert!(json.get("title").is_none(), "None title must be omitted");
    }

    #[test]
    fn json_round_trip_preserves_model() {
        let model = sample_model();
        let json = serde_json::to_string(&model).unwrap();
        let back: VaultModel = serde_json::from_str(&json).unwrap();
        assert_eq!(model, back);
    }

    /// Property 1 (Round-trip fidelity): for a valid model, compress+serialize
    /// then decompress+deserialize yields the identical model.
    ///
    /// **Validates: Requirements 5.4, 7.6, 12.5**
    #[test]
    fn serialize_compress_round_trip_is_lossless() {
        let model = sample_model();

        let bytes = serialize_vault(&model).unwrap();
        let back = deserialize_vault(&bytes).unwrap();

        assert_eq!(model, back, "deserialize(serialize(m)) must equal m");
    }

    #[test]
    fn empty_model_round_trips_through_compression() {
        let model = VaultModel::new();
        let bytes = serialize_vault(&model).unwrap();
        let back = deserialize_vault(&bytes).unwrap();
        assert_eq!(model, back);
    }

    #[test]
    fn serialized_output_is_compressed_not_raw_json() {
        let model = sample_model();
        let raw_json = serde_json::to_vec(&model).unwrap();
        let compressed = serialize_vault(&model).unwrap();
        // The zlib output should differ from the raw JSON bytes.
        assert_ne!(compressed, raw_json);
    }

    #[test]
    fn deserialize_rejects_corrupt_compressed_bytes() {
        // Not a valid zlib stream.
        let garbage = vec![0xFF, 0x00, 0x12, 0x34, 0x56];
        let err = deserialize_vault(&garbage).unwrap_err();
        assert!(matches!(err, ModelError::Compression(_)));
    }

    #[test]
    fn deserialize_rejects_valid_compression_with_invalid_json() {
        // Compress bytes that are not valid JSON, then attempt to deserialize.
        let mut encoder = ZlibEncoder::new(Vec::new(), Compression::default());
        encoder.write_all(b"this is not json").unwrap();
        let bytes = encoder.finish().unwrap();

        let err = deserialize_vault(&bytes).unwrap_err();
        assert!(matches!(err, ModelError::Json(_)));
    }

    #[test]
    fn all_field_types_round_trip() {
        let types = [
            FieldType::Email,
            FieldType::Username,
            FieldType::Password,
            FieldType::Phone,
            FieldType::Url,
            FieldType::Text,
            FieldType::Note,
            FieldType::TotpSecret,
            FieldType::RecoveryCode,
        ];
        for t in types {
            let s = serde_json::to_string(&t).unwrap();
            let back: FieldType = serde_json::from_str(&s).unwrap();
            assert_eq!(t, back);
        }
    }
}
