//! Bundled service catalog (Req 6.1, 12.1–12.4).
//!
//! Keyhaven ships a curated, **fully offline** catalog of popular services so
//! the user can pick a service (with a sensible set of recommended fields and an
//! icon) without any network access (Req 12.1). The catalog is generated by a
//! dev-only Node script (`tools/build-catalog.mjs`); only its JSON/icon output
//! is shipped under `src-tauri/catalog/`.
//!
//! ## Loading "at startup" (Req 12.2, 12.4)
//!
//! The catalog JSON is embedded into the binary at **compile time** with
//! [`include_str!`], so there is no runtime path resolution, bundle-resource
//! lookup, or filesystem dependency — it works identically across platforms and
//! while completely offline. It is parsed **once** on first use and cached in a
//! [`OnceLock`], which is the practical equivalent of "loaded at startup": the
//! first call (e.g. the first `search_catalog`) populates the cache and every
//! subsequent call reuses it.
//!
//! ## Search (Req 6.1)
//!
//! [`search_catalog`] performs a case-insensitive substring match against each
//! service's display name **and** all of its aliases, so searching "gmail"
//! surfaces "Google". An empty/blank query returns the **entire** catalog (the
//! natural "browse everything" behavior the service picker uses before the user
//! types anything).
//!
//! ## Custom services (Req 6.2–6.5)
//!
//! User-defined services are **not** part of this bundled catalog: they are
//! persisted inside the encrypted vault model (`VaultModel.custom_services`) and
//! are created/listed by the command layer ([`crate::commands`]). Living in the
//! vault is exactly what marks a service as "custom"; the command layer adds an
//! explicit `custom: true` flag to the wire shape for the frontend.

// Some catalog helpers are consumed by the command layer / frontend and may not
// all be referenced from the binary while the core is built bottom-up.
#![allow(dead_code)]

use std::sync::OnceLock;

use serde::{Deserialize, Serialize};

use crate::model::FieldType;

/// The bundled catalog JSON, embedded at compile time (Req 12.2, 12.4).
///
/// Using [`include_str!`] keeps the catalog available offline with no runtime
/// path/bundle-resource concerns and works identically on every platform.
const CATALOG_JSON: &str = include_str!("../../catalog/services-catalog.json");

/// One recommended field for a catalog service: a suggested label + semantic
/// type + secrecy flag the UI pre-populates when the user picks the service.
///
/// Mirrors the JSON object shape exactly so it deserializes straight from the
/// bundled file. `field_type` is serialized/deserialized as `type` to match the
/// wire key (and the rest of the model's convention).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecommendedField {
    /// Suggested human-readable label (e.g. "Email").
    pub label: String,
    /// Semantic type of the field. (De)serialized as `type` on the wire.
    #[serde(rename = "type")]
    pub field_type: FieldType,
    /// Whether the field is sensitive by default (masking / clipboard / search).
    pub secret: bool,
}

/// A single bundled catalog service (Req 6.1).
///
/// Mirrors the JSON shape generated by the build script: `id`, display `name`,
/// `icon` filename (resolved against the bundled `catalog/icons/` set), search
/// `aliases`, and the `recommended_fields` to pre-populate a new entry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CatalogService {
    /// Stable catalog identifier (e.g. `"google"`), referenced by
    /// [`crate::model::ServiceRef::Catalog`].
    pub id: String,
    /// Display name (e.g. "Google").
    pub name: String,
    /// Bundled icon filename (e.g. `"google.svg"`).
    pub icon: String,
    /// Inline brand-logo SVG markup (already brand-colored). Empty when no
    /// vector logo is bundled; the UI then falls back to `icon_data` or a
    /// monogram.
    #[serde(default)]
    pub svg: String,
    /// The logo's primary hex color (e.g. `"#4285f4"`), used by the UI to tint
    /// the icon tile. Empty when unknown.
    #[serde(default)]
    pub color: String,
    /// A raster logo as a `data:` URL (a bundled favicon), used for brands with
    /// no vector logo available. Empty when none.
    #[serde(default)]
    pub icon_data: String,
    /// Alternative search terms (e.g. `["gmail", "gsuite"]`).
    #[serde(default)]
    pub aliases: Vec<String>,
    /// Recommended fields to pre-populate when this service is chosen.
    #[serde(default)]
    pub recommended_fields: Vec<RecommendedField>,
}

/// Process-wide cache of the parsed catalog, populated once on first access.
static CATALOG: OnceLock<Vec<CatalogService>> = OnceLock::new();

/// Borrow the bundled catalog, parsing the embedded JSON on first use and
/// caching the result for every subsequent call (Req 12.2).
///
/// The embedded JSON is generated/validated by the build tooling and is part of
/// the shipped binary, so a parse failure here is a build/packaging bug rather
/// than a runtime condition — hence the `expect`. (The
/// [`bundled_catalog_parses`](tests::bundled_catalog_parses) test guards against
/// ever shipping a malformed file.)
pub fn catalog() -> &'static [CatalogService] {
    CATALOG.get_or_init(|| {
        serde_json::from_str::<Vec<CatalogService>>(CATALOG_JSON)
            .expect("bundled services-catalog.json must be valid")
    })
}

/// Case-insensitive search over the bundled catalog by name **and** aliases
/// (Req 6.1).
///
/// Matching semantics:
/// - The query is trimmed and lowercased; a service matches when the query is a
///   substring of its lowercased `name` or of any lowercased alias.
/// - An **empty or whitespace-only** query returns the entire catalog (in its
///   bundled order), so the picker can show everything before the user types.
///
/// Results preserve the catalog's bundled order.
pub fn search_catalog(query: &str) -> Vec<CatalogService> {
    let needle = query.trim().to_lowercase();
    let all = catalog();

    if needle.is_empty() {
        return all.to_vec();
    }

    all.iter()
        .filter(|service| service_matches(service, &needle))
        .cloned()
        .collect()
}

/// Whether `service`'s name or any of its aliases contains the already-lowercased
/// `needle` as a substring.
fn service_matches(service: &CatalogService, needle: &str) -> bool {
    if service.name.to_lowercase().contains(needle) {
        return true;
    }
    service
        .aliases
        .iter()
        .any(|alias| alias.to_lowercase().contains(needle))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The bundled JSON must parse into a plausible-sized catalog (Req 12.2,
    /// 12.4). Guards against shipping a malformed or truncated file.
    #[test]
    fn bundled_catalog_parses() {
        let services = catalog();
        assert!(
            services.len() >= 50,
            "expected a substantial bundled catalog, got {}",
            services.len()
        );
        // Every entry has the core fields populated.
        for service in services {
            assert!(!service.id.is_empty(), "service id must not be empty");
            assert!(!service.name.is_empty(), "service name must not be empty");
            assert!(!service.icon.is_empty(), "service icon must not be empty");
        }
    }

    #[test]
    fn search_matches_by_name_case_insensitively() {
        // Mixed-case query still matches the "Google" service by name.
        let results = search_catalog("GOoGlE");
        assert!(
            results.iter().any(|s| s.id == "google"),
            "expected to find Google by name regardless of case"
        );
    }

    #[test]
    fn search_matches_by_alias() {
        // "gmail" is an alias of Google, not its name.
        let results = search_catalog("gmail");
        assert!(
            results.iter().any(|s| s.id == "google"),
            "expected to find Google via its 'gmail' alias"
        );
    }

    #[test]
    fn search_matches_partial_substring() {
        // A substring of the name ("oogl") still matches.
        let results = search_catalog("oogl");
        assert!(results.iter().any(|s| s.id == "google"));
    }

    #[test]
    fn search_no_match_returns_empty() {
        let results = search_catalog("zzzz-no-such-service-zzzz");
        assert!(
            results.is_empty(),
            "a query matching nothing must return an empty list"
        );
    }

    #[test]
    fn empty_query_returns_entire_catalog() {
        let all = catalog().len();
        assert_eq!(
            search_catalog("").len(),
            all,
            "empty query returns the whole catalog"
        );
        assert_eq!(
            search_catalog("   ").len(),
            all,
            "whitespace-only query is treated as empty and returns everything"
        );
    }

    #[test]
    fn recommended_fields_deserialize_with_field_types() {
        // Google should carry recommended fields including secret/typed ones,
        // confirming the `type` rename + FieldType reuse deserialize correctly.
        let google = catalog()
            .iter()
            .find(|s| s.id == "google")
            .expect("google must be present");
        assert!(
            !google.recommended_fields.is_empty(),
            "google should have recommended fields"
        );
        // At least one password/secret field is expected.
        assert!(
            google
                .recommended_fields
                .iter()
                .any(|f| f.field_type == FieldType::Password),
            "expected a password recommended field"
        );
    }

    #[test]
    fn catalog_is_cached_and_stable_across_calls() {
        // Two calls return the same content (and the cache pointer is stable).
        let a = catalog();
        let b = catalog();
        assert_eq!(a.len(), b.len());
        assert!(std::ptr::eq(a.as_ptr(), b.as_ptr()), "catalog must be cached");
    }
}
